### ISSUE TITLE
increasing number of finished_execute.CodeCell events

### ISSUE THREAD

**Issue by juhasch** [jfbercher/jupyter_varInspector#2]
If you execute this snippet with notebook 5.0, you will get a log whenever a call is executed:
```Python
%%javascript

require(['base/js/events'], function(events) 
    {
    events.on('finished_iopub.Kernel', function(evt){ console.log('finished_iopub.Kernel', evt)})
    events.on('finished_execute.CodeCell', function(evt){ console.log('finished_execute.CodeCell', evt)})
    })

```

With varInspector enabled, the number of `finished_execute.CodeCell` events increases after every execution of a code cell (first execution: one eventl, second execution: two events, etc.)

**Comment by jfbercher** [comment]
Right. But actually, it seems to be also the case without varinspector. No?
This is perhaps due to some other extension.

**Comment by juhasch** [comment]
You are right, I can reproduce it without varInspector. Thanks for looking into it.
Maybe it was too late last evening...

I will open a new issue in notebook.
